import os
from os import getenv
from dotenv import load_dotenv

if os.path.exists("local.env"):
    load_dotenv("local.env")
 
STRING_SESSION1 = getenv("STRING_SESSION1", "BQGMcpgAb2GEqlSiGeX2N5PMIAoV-UPAWqqwDDjO-4jYUGUrurfm3s2YWwjKj5v8DfNYeQavmx94VJTIROf8zyBP4dTCf791Uw2UUObP0JLSo_AhPKqmHERB01jEd6pUBtxpBRWiBu1xCElvCfU027fY_6yUh8BMsXvw9UIOA4NWI437i3g_bh45gBIs_Ob4KrWDxYEdgYMgOrG2MlvwKrQD1y8pPgtT_jfYJLu5vFQqdR9NnW3DU7rpSI_gFJ7QgL1i8XOdAXHnuxucGcrc6f__I51wu052F9cI929nzCIpScfQfOm1VjHEXd8_UzcKZe7ShcwTk7l2584qXIvA-8xJhyYa0gAAAAHDoqu_AA")
STRING_SESSION2 = getenv("STRING_SESSION2", "")
STRING_SESSION3 = getenv("STRING_SESSION3", "")
STRING_SESSION4 = getenv("STRING_SESSION4", "")
STRING_SESSION5 = getenv("STRING_SESSION5", "")
STRING_SESSION6 = getenv("STRING_SESSION6", "")
STRING_SESSION7 = getenv("STRING_SESSION7", "")
STRING_SESSION8 = getenv("STRING_SESSION8", "")
STRING_SESSION9 = getenv("STRING_SESSION9", "")
STRING_SESSION10 = getenv("STRING_SESSION10", "")
